### ISSUE TITLE
Tips appreciated porting this to OpenCL

### ISSUE THREAD

**Issue by MyNameIsTrez** [djns99/CUDA-Shuffle#11]
Hello,

I've read your paper and am absolutely ecstatic about using it to replace my slow CPU-based Fisher–Yates shuffle!

I'm sorting the pixels of an image by (CIELAB) color, and I am doing so by repeatedly attempting to swap two random pixels.
Before a swap is performed, it evaluates whether it'd "improve" the image. This is done using an NxN kernel around the two potentially swapped pixels, which are used to check if the total color difference to their neighbors would become lower after the swap.
The intuition being that if you have a red pixel surrounded by blue pixels, the red pixel would be perceived as an eyesore, and should ideally be swapped somewhere more reddish:

https://user-images.githubusercontent.com/32989873/207989595-ef8dee15-b65b-460a-a1aa-a7f1378e4bd0.mp4

This simple algorithm works really well, because pixels have a chance to go from one side of the image all the way to the other within a single swap. You can imagine the exact opposite approach of only allowing pixels to be swapped with their eight neighbors resulting in the program immediately getting stuck in local optima. But because I generate the pixel indices to be swapped with Fisher-Yates, I am pretty confident I should be able to gain at least an order of magnitude of performance by rewriting the entire program to take place on the GPU. But shuffling on the GPU seems infinitely more complex than the dumb eight neighbor approach, since GPUs seem to fight to their dying breath against having randomness run on them.

I don't have any prior experience with OpenCL/CUDA, and I only have an AMD GPU with Windows 10, so I'm trying to figure out how I should adopt your code. This is the PyOpenCL code I've got working right now:

```py
import os
from pathlib import Path

import numpy as np
import pyopencl as cl

arr_np = np.random.rand(5).astype(np.float32)

# This environment variable needs to be set
# to let pyopencl not ask which platform (GPU) to use
os.environ["PYOPENCL_CTX"] = "0"
ctx = cl.create_some_context()

queue = cl.CommandQueue(ctx)

mf = cl.mem_flags
arr = cl.Buffer(ctx, mf.READ_WRITE | mf.COPY_HOST_PTR, hostbuf=arr_np)

opencl_code = """
__kernel void shuffle_(
	__global float *arr
) {
	int i = get_global_id(0);
	arr[i] *= 2;
}
"""

prg = cl.Program(ctx, opencl_code).build()

knl = prg.shuffle_
knl(queue, arr_np.shape, None, arr)

res_np = np.empty_like(arr_np)
cl.enqueue_copy(queue, res_np, arr)

print(arr_np)
print(res_np)
```

Because this repo depends on other CUDA headers I'm afraid I'd have to rewrite all of those as well, which isn't really feasible, especially with the bugs I'd inevitably introduce by manually trying to port the CUDA shuffling code alone.

Any tips on how I should do shuffling on the GPU, and tips on my color sorting project in general? :)

**Comment by MyNameIsTrez** [comment]
@djns99 @RAMitchell Pinging in case you both have notifications turned off for this repo's Issues page

**Comment by djns99** [comment]
Thanks for getting in touch @MyNameIsTrez. The core idea behind our approach is using a block cipher to 'encrypt' the input index. Since this is reversible we can guarantee that the output for each element will be unique (i.e. you wont generate the same index twice). We then do a scan to get rid of out of bounds elements (since most block ciphers only work on powers of two).

To clarify, As I understand it you want to shuffle pixel indices and then swap each neighboring pair so that you can swap each pixel once.

In your situation you can avoid the scan by repeatedly applying the cipher until its in range. This may make the performance non-deterministic, but it can make the algorithm simpler to implement if you don't already have a scan implementation like thrust has.

```c++
int getShuffledIndex(int i, int num_pixels) {
  assert( i < num_pixels);
  int shuffled = i;

  // This loop is guaranteed to terminate if i < num_pixels
  do {
   shuffled = philox( shuffled );
  } while( shuffled >= num_pixels );
 return shuffled;
}

void runColourSwapAlgorithm(float* image, int num_pixels) {
   int i1 = get_global_index(0) * 2; // Launch half as many threads as pixels
   int i2 = i1+1;
  
   // This calculates the i1-th and i2-th shuffle indices right here. You don't even need an array :)
   int shuffled_index1 = getShuffledIndex( i1 );
   int shuffled_index2 = getShuffledIndex( i2 );
 
  // This is your own logic to check if you should swap the selected indices
  if( shouldSwap( image, shuffled_index1 , shuffled_index2 ) )
    swap( image,  shuffled_index1 , shuffled_index2 );
}
```

The `philox` function used in `getShuffledIndex` is our recommended cipher. You can see an example implementation in the `operator()` for `include/shuffle/PhiloxShuffle.h`. If you care more about performance and less about getting high quality random numbers you can look at the LCG Bijective shuffle implementation.

Hopefully this is enough to get you started.

**Comment by MyNameIsTrez** [comment]
Holy crap, I didn't expect such a quick response, let alone such an accurate and elegant code snippet. Thank you; that code is exactly what I had in mind! :D

I think I'll start off with the LCG Bijective shuffle, since it's less code for me to mess up porting, and then once I got that working I can port philox and compare the two.

Both the LCG Bijective shuffle and philox tests seem to use the DefaultRandomGenerator everywhere, so I'll have to replicate that. I thought that OpenCL didn't support C++, but I just found [this page](https://github.com/KhronosGroup/OpenCL-Guide/blob/main/chapters/cpp_for_opencl.md) stating that it is definitely possible to run C++, so I guess I can try that to make porting of the CUDA DefaultRandomGenerator class slightly easier.

I'll keep this thread updated with questions and progress updates!

**Comment by MyNameIsTrez** [comment]
@djns99 So I have tried to port your `LCGBijectiveFunction`, and for now I'm just attempting to have the image's pixels be completely randomly shuffled. But I have no clue what I should replace `random_function()` here with:

![image](https://github.com/djns99/CUDA-Shuffle/assets/32989873/abedf092-1b11-4bed-9585-af1e6719cf41)

So I've just used some random values for them for now:

![image](https://github.com/djns99/CUDA-Shuffle/assets/32989873/c0cd9ee1-bb46-42d9-8ca2-adabe1230425)

With this as the input image:

![elephant](https://github.com/djns99/CUDA-Shuffle/assets/32989873/bb29071b-bbb1-411f-8ad6-eeb1230616ef)

This becomes the output image:

![elephant](https://github.com/djns99/CUDA-Shuffle/assets/32989873/b0201179-f96e-4218-9e8c-1537f3e0710d)

This is a bad result, since I wanted to end up with pure noise here, rather than with obvious stripes. And I don't understand why the elephant's head seems to just be shifted to the bottom-right. But I know that LCGs are notoriously awful, so I don't know if better `multiplier_rand` and `addition_rand` would improve the result considerably.

I would also appreciate advice on whether I should be letting the swapping of every pixel happen just once per Python kernel call, or whether I should do something like adding a for-loop in the `.cl` code that wraps it all. The former seems unnecessarily slow, since I want to call the kernel code as many times as possible per second. And for the latter you'd think there'd be a neater solution, like telling OpenCL to repeat it 1 million times before returning to Python using a function parameter?

I am pretty confident that the bad result is either due to `lcg()` or `get_shuffled_index()`, since the output image is identical to the input image if I change the `write_imageui(dest, pos1, pix2)` to `write_imageui(dest, pos1, pix1)`, and I do the same for `pos2`.

Here is the OpenCL code, which you can also find [in my repository](https://github.com/MyNameIsTrez/pyopencl-color-sorter). Any tips are appreciated! I'll start porting your `PhiloxBijectiveFunction` meanwhile, but because it also uses `random_function()` I don't know how to properly port that one either.

```opencl
#define uint64_t ulong

uint64_t round_up_power_2(
	uint64_t a
) {
	if(a & (a - 1))
	{
		uint64_t i;
		for(i = 0; a > 1; i++)
		{
			a >>= 1ull;
		}

		return 1ull << (i + 1ull);
	}

	return a;
}

uint64_t lcg(
	uint64_t capacity,
	uint64_t val
) {
	uint64_t modulus = round_up_power_2(capacity);

	// TODO: Ask authors what I should do in place of random_function() here:
	uint64_t multiplier_rand = 42424242;

	// Must be odd so it is coprime to modulus
	uint64_t multiplier = (multiplier_rand * 2 + 1) % modulus;

	// TODO: Ask authors what I should do in place of random_function() here:
	uint64_t addition_rand = 69696969;

	uint64_t addition = addition_rand % modulus;

	// Modulus must be power of two
	// assert((modulus & (modulus - 1)) == 0);
	// TODO: Replace with proper assert() somehow
	if (!((modulus & (modulus - 1)) == 0)) {
		printf("Assertion failure: Modulus wasn't power of two!\n");
	}

	return ((val * multiplier) + addition) & (modulus - 1);
}

int2 get_pos(
	int shuffled_i,
	int width
) {
	int x = shuffled_i % width;
	int y = (int)(shuffled_i / width);
	return (int2)(x, y);
}

void swap(
	read_only image2d_t src,
	write_only image2d_t dest,
	int width,
	int shuffled_i1,
	int shuffled_i2
) {
	int2 pos1 = get_pos(shuffled_i1, width);
	int2 pos2 = get_pos(shuffled_i2, width);

	// CLK_NORMALIZED_COORDS_FALSE means the x and y coordinates won't be normalized to between 0 and 1
	// CLK_ADDRESS_CLAMP_TO_EDGE means the x and y coordinates are clamped to be within the image's size
	// CLK_FILTER_NEAREST means not having any pixel neighbor interpolation occur
	// Sources:
	// https://man.opencl.org/sampler_t.html
	// https://registry.khronos.org/OpenCL/specs/opencl-1.1.pdf
	sampler_t sampler = CLK_NORMALIZED_COORDS_FALSE | CLK_ADDRESS_CLAMP_TO_EDGE | CLK_FILTER_NEAREST;

	uint4 pix1 = read_imageui(src, sampler, pos1);
	uint4 pix2 = read_imageui(src, sampler, pos2);

	write_imageui(dest, pos1, pix2);
	write_imageui(dest, pos2, pix1);
}

int get_shuffled_index(
	int i,
	int num_pixels
) {
	// assert(i < num_pixels);
	// TODO: Replace with proper assert() somehow
	if (!(i < num_pixels)) {
		printf("Assertion failure: i < num_pixels was false!\n");
	}
	int shuffled = i;

	// This loop is guaranteed to terminate if i < num_pixels
	do {
		shuffled = lcg(num_pixels, shuffled);
	} while (shuffled >= num_pixels);

	return shuffled;
}

kernel void shuffle_(
	read_only image2d_t src,
	write_only image2d_t dest
) {
	// TODO: Test if using get_image_dim() instead of these two calls is faster
	int width = get_image_width(src);
	int height = get_image_height(src);

	int pixel_count = width * height;

	int gid = get_global_id(0);
	int i1 = gid * 2;
	int i2 = i1 + 1;

	int shuffled_i1 = get_shuffled_index(i1, pixel_count);
	int shuffled_i2 = get_shuffled_index(i2, pixel_count);
	swap(src, dest, width, shuffled_i1, shuffled_i2);
}
```

**Comment by MyNameIsTrez** [comment]
Added a small Python script that generates a 4k x 4k image containing all 16 million RGB colors:

![all_colors](https://github.com/djns99/CUDA-Shuffle/assets/32989873/e50bbdc1-f609-4bb4-bb6d-ec69444bfbc2)

After shuffling with the LCG it looks like so:
![all_colors](https://github.com/djns99/CUDA-Shuffle/assets/32989873/04a6bd94-3186-4d9f-97b5-8c519d837cfe)

Zooming that image in, we see it contains lots of stripes:
![all_colors_lcg_zoomed](https://github.com/djns99/CUDA-Shuffle/assets/32989873/565ee871-046b-4e89-88c3-cb6cb9417679)

I didn't expect the rectangular patterns to remain *this* clearly using your LCG, so I really think I just messed up the implementation of it somehow?

I also added a Python script that verifies the color occurrences of the input and output are identical, and the LCG as you stated always passes it, which is at least good.

**Comment by MyNameIsTrez** [comment]
@djns99 I got `PhiloxBijectiveFunction`, aka `philox()` working! 🥳 

Here's the 4k x 4k result cropped to 1k x 1k, since the full result is now so noisy that GitHub doesn't allow me to upload it:

![all_colors_sixteenth](https://github.com/djns99/CUDA-Shuffle/assets/32989873/ac5b6e9c-7adc-4e8b-bbe8-e69437bb6d72)

I still find it odd how terribly the LCG fared, but I wanted to end up using philox() anyways, so it's not that big of a deal to me.

`PhiloxBijectiveFunction` its `init()` method contains this:
`key[i] = random_function();`
so for now I replaced that with
`key[i] = 42424242;`
but I'd still absolutely love to know what I should've used here instead!

All that's left is implementing `shouldSwap()` by implementing a kernel using two for-loops to inspect the neighboring pixels, but if you have any optimizing tips I'd absolutely love to hear them! :)

**Comment by MyNameIsTrez** [comment]
I think in terms of functionality I'm done, apart from comparing colors in CIELAB instead of RGB!

I replaced the `random_function()` with a proper random function I found on StackOverflow.

Using that random function, the LCG creates nearly identical results roughly as fast as philox, so I've described in the README how to switch between which is used.

[Here's the link](https://github.com/MyNameIsTrez/pyopencl-color-sorter) so you can try it out and give (performance) tips! :)

![image](https://github.com/djns99/CUDA-Shuffle/assets/32989873/5d242e9f-d2b3-4c58-94d5-626803465a19)

**Comment by djns99** [comment]
Hi @MyNameIsTrez I'm glad you got it working!

With regards to the `init()` function: This is called once, before the kernel is run, to initialize a random state that is the same on all the threads. Changing what `key[i]`/`multiplier` is initialized to changes the result of your shuffle. It is important that all threads generate the same state or they wont generate unique indices and you may get race conditions. For example, with the LCG for a 16 pixel image:

> Index 2, with multiplier 3, addition 4: (2 * 3 + 4) = 10
> Index 3 with multiplier 5, addition 11: (3 * 5 + 11) = 26 % 16 = 10

So hardcoding 0x42424242 is a good initial approach. However, if you want to switch to a random state, which I see you have done in the latest version, you need to generate this outside the kernel and pass `key[NUM_ROUNDS]`/`multiplier` as a parameter, or use the same seed on all threads. You should be able to verify it is working by counting the number of pixels of each colour before and after.


Yes, I do expect the LCG to be that bad, especially if your image is already a power of two in size. Because we need it to be bijective (i.e. each index generates a unique output), the multiplier has to be coprime (i.e. have no common factors) with the modulus. To do this we always choose an odd multiplier (i.e. multiplier_rand * 2 + 1) and a power of two modulus, which do a poor job of mixing the data. See our paper https://arxiv.org/abs/2106.06161 for more in depth explanation. 
It may also be that your arbitrarily selected 42424242, is particularly bad. 
If you want to get marginally better results you could try multiple iterations of the LCG with different `multiplier`/`addition`. The proper way to get good results will be to pick a prime number slightly larger than your image as the modulus, then you can pick any multiplier less than the prime (except 0) and it should work better. Regardless, it is still not great.

Thanks for sharing your results!

**Comment by MyNameIsTrez** [comment]
I've finished up the project and added lots of pictures and videos to [the repository](https://github.com/MyNameIsTrez/pyopencl-color-sorter). 🥳
I couldn't get `philox()` working as well as `lcg()`, so I've decided to axe it for now. At least I don't have to maintain two algorithms now, and the noticeable patterns created by the poor quality of `lcg()` are fine in practice, due to 1 being added to the starting seed every iteration. It just means you need to run the program for a little longer. :)
Thanks again for the help!
